---
# tasks file for nginx

- name: install nginx
  yum: name=nginx
  become: yes

- name: start and enable nginx
  service: name=nginx state=started enabled=yes
  become: yes

# update default home page
- name: deploy customized home page
  copy:
    src: nginx_home.html
    dest: /usr/share/nginx/html/index.html
  become: yes
  notify:
    - restart nginx
