---
# tasks file for nginx-test

- name: check nginx's status
  shell: systemctl status nginx
  register: status
  become: yes

- debug:
    msg: "{{ status.stdout }}"

- name: test nginx
  shell: curl localhost
  register: test_nginx
  args:
    warn: false

- debug:
    msg: "{{ test_nginx.stdout }}"
